CREATE PROCEDURE SP_CARGA_TB_PRODUTOS_AUX(@DATACARGA DATETIME) AS
BEGIN
	DELETE FROM TB_Produto WHERE  DATA_CARGA = @DATACARGA
	DECLARE @DATAVENDA DATETIME, @IDPRODUTO INT,@NOME VARCHAR(45), @CATEGORIA VARCHAR(45), @STATUS_PRODUTO VARCHAR(25)

	DECLARE C_CARGA_PRODUTOS CURSOR FOR SELECT idProduto, nome, categoria, status_produto FROM TB_Produto;
	OPEN C_CARGA_PRODUTOS
		FETCH C_CARGA_PRODUTOS INTO @IDPRODUTO, @NOME, @CATEGORIA, @STATUS_PRODUTO
		WHILE(@@FETCH_STATUS = 0 )
		BEGIN
			INSERT INTO TB_Produto_AUX VALUES(@DATACARGA, @IDPRODUTO, @NOME, @CATEGORIA, @STATUS_PRODUTO);
			FETCH C_CARGA_PRODUTOS INTO @IDPRODUTO, @NOME, @CATEGORIA, @STATUS_PRODUTO
		END
	CLOSE C_CARGA_PRODUTOS
	DEALLOCATE C_CARGA_PRODUTOS
END



EXEC SP_CARGA_TB_PRODUTOS_AUX '20170920'