

---------------------------------------------------
--CARGA DA TB_CLIENTE PARA STAGING TB_CLIENTE_AUX
----------------------------------------------------

ALTER PROCEDURE SP_OLTP_TB_CLIENTE_AUX(@DATACARGA DATETIME) AS
BEGIN

	DELETE FROM TB_Cliente_AUX WHERE  DATA_CARGA = @DATACARGA

	DECLARE @IDCLIENTE INT,@NOME VARCHAR(45), @DATANASCIMENTO DATETIME, @MATRICULA INT, @EMAIL VARCHAR(45), @RUA VARCHAR(45), @BAIRRO VARCHAR(45), @CEP VARCHAR(45), @CIDADE VARCHAR(45),@ESTADO VARCHAR(45),@SEXO CHAR(1),@CPF VARCHAR(45),@RG INT 

	DECLARE CR_INSERT_CLIENTE CURSOR FOR 
	SELECT idCliente, nome, dataNascimento, Matricula, email, rua, bairro, cep, cidade, estado, sexo, CPF, RG FROM  TB_Cliente
	
	OPEN CR_INSERT_CLIENTE

		FETCH CR_INSERT_CLIENTE INTO @IDCLIENTE, @NOME, @DATANASCIMENTO, @MATRICULA, @EMAIL, @RUA, @BAIRRO, @CEP, @CIDADE, @ESTADO, @SEXO, @CPF,@RG
		
		WHILE(@@FETCH_STATUS = 0 )
		BEGIN
			INSERT TB_Cliente_AUX (idCliente, DATA_CARGA, nome, dataNascimento, Matricula, email, rua, bairro, cep, cidade, estado, sexo, CPF, RG) VALUES(@IDCLIENTE, @DATACARGA, @NOME, @DATANASCIMENTO, @MATRICULA, @EMAIL, @RUA, @BAIRRO, @CEP, @CIDADE, @ESTADO, @SEXO, @CPF,@RG)
			
			FETCH CR_INSERT_CLIENTE INTO @IDCLIENTE, @NOME, @DATANASCIMENTO, @MATRICULA, @EMAIL, @RUA, @BAIRRO, @CEP, @CIDADE, @ESTADO, @SEXO, @CPF,@RG
		END
	CLOSE CR_INSERT_CLIENTE
	DEALLOCATE CR_INSERT_CLIENTE
END
INSERT INTO TB_Cliente VALUES ('ESO','19840611',1234,'ESODEGEMEOS@GMAIL.COM','RUA A','CENTRO','49.500-000','ITABAIANA','SERGIPE','M','000.000.000-00',54321)
SELECT * FROM TB_Cliente
select * from TB_Cliente_AUX
EXEC SP_OLTP_TB_CLIENTE_AUX '20170923'

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------
--CARGA DA TB_PRODUTO PARA STAGING TB_PRODUTO_AUX
----------------------------------------------------

ALTER PROCEDURE SP_OLTP_AUX_PRODUTO(@DATACARGA DATETIME) AS
BEGIN

	DELETE FROM TB_Produto_AUX WHERE  DATA_CARGA = @DATACARGA

	DECLARE @IDPRODUTO INT,@NOME VARCHAR(45), @CATEGORIA VARCHAR(45), @STATUS_PRODUTO VARCHAR(25)

	DECLARE CR_INSERT_PRODUTO CURSOR FOR SELECT P.idProduto, P.nome,P.categoria,P.status_produto FROM  TB_Produto P;
	OPEN CR_INSERT_PRODUTO

		FETCH CR_INSERT_PRODUTO INTO @IDPRODUTO,@NOME, @CATEGORIA, @STATUS_PRODUTO
		WHILE(@@FETCH_STATUS = 0 )
		BEGIN
			INSERT TB_Produto_AUX (idProduto,DATA_CARGA,NOME,categoria,status_produto) VALUES(@IDPRODUTO,@DATACARGA, @NOME, @CATEGORIA, @STATUS_PRODUTO)
			FETCH CR_INSERT_PRODUTO INTO @IDPRODUTO,@NOME, @CATEGORIA, @STATUS_PRODUTO
		END
	CLOSE CR_INSERT_PRODUTO
	DEALLOCATE CR_INSERT_PRODUTO
END

SELECT * FROM TB_Produto
select * from TB_Produto_AUX
INSERT INTO TB_Produto VALUES ('AAAAA','BBBBB','COM DEFEITO')
EXEC SP_OLTP_AUX_PRODUTO '20170923'



--------------------------------------------------------------------------------------------------------------------

---------------------------------------------------
--CARGA DA TB_TIPO_PAGAMENTO PARA STAGING TB_TIPO_PAGAMENTO_AUX
----------------------------------------------------


ALTER PROCEDURE SP_OLTP_TB_TIPO_PAGAMENTO_AUX (@DATACARGA DATETIME) AS
BEGIN

	DELETE FROM TB_TIPO_PAGAMENTO_AUX WHERE DATA_CARGA = @DATACARGA

	DECLARE @IDTIPOPAGAMENTO INT,@COD_TIPOPAGAMENTO INT, @TIPOPAGAMENTO VARCHAR(25)

	DECLARE CR_INSERT_TIPO_PAGAMENTO CURSOR FOR SELECT TP.ID_TIPO_PAGAMENTO, TP.COD_TIPO_PAGAMENTO, TP.TIPO_PAGAMENTO FROM  TB_TIPO_PAGAMENTO TP;
	OPEN CR_INSERT_TIPO_PAGAMENTO

		FETCH CR_INSERT_TIPO_PAGAMENTO INTO @IDTIPOPAGAMENTO, @COD_TIPOPAGAMENTO, @TIPOPAGAMENTO
		WHILE(@@FETCH_STATUS = 0 )
		BEGIN
			INSERT TB_TIPO_PAGAMENTO_AUX (DATA_CARGA, ID_TIPO_PAGAMENTO, COD_TIPO_PAGAMENTO, TIPO_PAGAMENTO) VALUES(@DATACARGA, @IDTIPOPAGAMENTO, @COD_TIPOPAGAMENTO, @TIPOPAGAMENTO)
			FETCH CR_INSERT_TIPO_PAGAMENTO INTO @IDTIPOPAGAMENTO, @COD_TIPOPAGAMENTO, @TIPOPAGAMENTO
		END
	CLOSE CR_INSERT_TIPO_PAGAMENTO
	DEALLOCATE CR_INSERT_TIPO_PAGAMENTO
END

SELECT * FROM TB_TIPO_PAGAMENTO
select * from TB_TIPO_PAGAMENTO_AUX
INSERT INTO TB_TIPO_PAGAMENTO VALUES (12345,'DINHEIRO'),
									 (00000,'CARTÃO A VISTA')

EXEC SP_OLTP_TB_TIPO_PAGAMENTO_AUX '20170923'

-------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------
--CARGA DA TB_TRANSPORTE PARA STAGING TB_TRANSPORTE_AUX
----------------------------------------------------

--DUVIDA: OS IDS DE LOCAÇÃO E DE VENDAS TEM QUE SER COLOCADOS PRA SERE INSERIDOS TBM?
--PROCEDURE FUNCIONA MAS NÃO INSERE NADA NA TB_TRANSPORTE PORQUE PRACISA DOS IDS DAS CHAVES ESTRANGEIRAS 
ALTER PROCEDURE SP_OLTP_AUX_TB_TRANSPORTE_AUX(@DATACARGA DATETIME) AS
BEGIN

	DELETE FROM TB_Transporte_AUX WHERE  DATA_CARGA = @DATACARGA

	DECLARE @IDTRANSPORTE INT,@CODIGOTRANSPORTE INT, @TRANSPORTE VARCHAR(25), @ENDERECOFESTA VARCHAR(45),@IDLOCACAO INT, @IDVENDA INT

	DECLARE CR_INSERT_TRANSPORTE CURSOR FOR SELECT T.idTransporte, T.codigoTransporte, T.transporte, T.EnderecoFesta, T.idLocacao, T.idVenda FROM TB_Transporte T;
	OPEN CR_INSERT_TRANSPORTE

		FETCH CR_INSERT_TRANSPORTE INTO @IDTRANSPORTE,@CODIGOTRANSPORTE, @TRANSPORTE, @ENDERECOFESTA,@IDLOCACAO, @IDVENDA
		WHILE(@@FETCH_STATUS = 0 )
		BEGIN
			INSERT TB_Transporte_AUX (idTransporte,DATA_CARGA,codigoTransporte,transporte,EnderecoFesta,idLocacao,idVenda) VALUES(@IDTRANSPORTE, @DATACARGA, @CODIGOTRANSPORTE, @TRANSPORTE, @ENDERECOFESTA,@IDLOCACAO, @IDVENDA)
			FETCH CR_INSERT_TRANSPORTE INTO @IDTRANSPORTE,@CODIGOTRANSPORTE, @TRANSPORTE, @ENDERECOFESTA,@IDLOCACAO, @IDVENDA
		END
	CLOSE CR_INSERT_TRANSPORTE
	DEALLOCATE CR_INSERT_TRANSPORTE
END

SELECT * FROM TB_Transporte
select * from TB_Transporte_AUX
SELECT * FROM TB_Locacao
SELECT * FROM TB_Vendas
INSERT INTO TB_Transporte (codigoTransporte,transporte,EnderecoFesta,idLocacao,idVenda) VALUES (12345,'Presencial','RUA DAS PIGUELAS CAIDAS 5151',1,3),
								 (54321,'Domicilio','RUA DOS FURUNFA MOELA372',1,3)
EXEC SP_OLTP_AUX_TB_TRANSPORTE_AUX '20170924'


--------------------------------------------------------------------------------------------------------------------

---------------------------------------------------
--CARGA DA TB_VENDEDORES PARA STAGING TB_VENDEDORES_AUX
----------------------------------------------------

--DUVIDA: OS IDS DE LOCAÇÃO E DE VENDAS TEM QUE SER COLOCADOS PRA SERE INSERIDOS TBM?

CREATE PROCEDURE SP_OLTP_AUX_TB_VENDEDORES_AUX(@DATACARGA DATETIME) AS
BEGIN
	DELETE FROM TB_Vendedores_AUX WHERE  DATA_CARGA = @DATACARGA

	DECLARE @IDVENDEDORES INT,@NOME VARCHAR(45), @MATRICULA INT, @LOGIN VARCHAR(45), @SENHA VARCHAR(45), @EMAIL VARCHAR(45), @TELEFONE VARCHAR(45), @SEXO CHAR(1), @RUA VARCHAR(45), @BAIRRO VARCHAR(45), @CEP VARCHAR(45), @CIDADE VARCHAR(45), @UF VARCHAR(2), @RG INT, @CPF VARCHAR(45)

	DECLARE CR_INSERT_VENDEDORES CURSOR FOR SELECT V.idVendedores, V.nome, V.matricula, V.login, V.senha, V.email, V.telefone, V.sexo, V.rua, V.bairro, V.cep, V.cidade, V.UF, V.RG, V.CPF FROM TB_Vendedores V;
	OPEN CR_INSERT_VENDEDORES

		FETCH CR_INSERT_VENDEDORES INTO @IDVENDEDORES, @NOME, @MATRICULA, @LOGIN, @SENHA, @EMAIL, @TELEFONE, @SEXO, @RUA, @BAIRRO, @CEP, @CIDADE, @UF, @RG, @CPF
		WHILE(@@FETCH_STATUS = 0 )
		BEGIN
			INSERT TB_VENDEDORES_AUX (idVendedores, DATA_CARGA, nome, matricula, login, senha, email, telefone, sexo, rua, bairro, cep, cidade, UF,RG, CPF) VALUES(@IDVENDEDORES,@DATACARGA, @NOME, @MATRICULA, @LOGIN, @SENHA, @EMAIL, @TELEFONE, @SEXO, @RUA, @BAIRRO, @CEP, @CIDADE, @UF, @RG, @CPF)
			FETCH CR_INSERT_VENDEDORES INTO @IDVENDEDORES, @NOME, @MATRICULA, @LOGIN, @SENHA, @EMAIL, @TELEFONE, @SEXO, @RUA, @BAIRRO, @CEP, @CIDADE, @UF, @RG, @CPF
		END
	CLOSE CR_INSERT_VENDEDORES
	DEALLOCATE CR_INSERT_VENDEDORES
END

SELECT * FROM TB_Vendedores
select * from TB_Vendedores_AUX
INSERT INTO TB_Vendedores (nome, matricula, login, senha, email, telefone, sexo, rua, bairro, cep, cidade, UF,RG, CPF)
 VALUES ('ESOX',098765,'EMESON','34567','PERAMORE.1@HOTMAIL.COM','12345-1234','M','RUAS DAS BUTEQQUEIRAS BELAS','ZONA QUENTE','44.444-555','FIM DAS BAXA GRANDE','CQ',7654,'111.111.111.-11')
							
								 
EXEC SP_OLTP_AUX_TB_VENDEDORES_AUX '20170923'

-------------------------------------------------------------------
--CARGA DA TB_VENDAS PARA STAGING TB_VENDAS_AUX
------------------------------------------------------------------
--NÃO INSERI NA TB_VENDAS PROCAUSA DAS CHAVES ESTRANGEIRAS
ALTER PROCEDURE SP_OLTP_TB_VENDAS_AUX (@DATACARGA DATETIME)
AS
BEGIN
 DELETE FROM TB_Vendas_AUX WHERE  DATA_CARGA = @DATACARGA
DECLARE @IDVENDA INT, @CODVENDA INT, @DATAVENDA DATETIME, @VALOR NUMERIC(10,2), @QUANTIDADE INT, @IDVENDEDORES INT, @IDCLIENTES INT
DECLARE CR_INSERT_VENDAS CURSOR FOR SELECT TV.idCliente, TV.cod_Venda, TV.dataVenda, TV.valor, TV.quantidade, TV.idVendedores, TV.idCliente FROM TB_Vendas TV;
	OPEN CR_INSERT_VENDAS

		FETCH CR_INSERT_VENDAS INTO @IDVENDA, @CODVENDA, @DATAVENDA, @VALOR, @QUANTIDADE, @IDVENDEDORES, @IDCLIENTES
		WHILE(@@FETCH_STATUS = 0 )
		BEGIN
			INSERT TB_Vendas_AUX (idVenda,DATA_CARGA, cod_Venda, dataVenda, valor, quantidade, idVendedores, idCliente) VALUES (@IDVENDA,@DATACARGA ,@CODVENDA, @DATAVENDA, @VALOR, @QUANTIDADE,@IDVENDEDORES, @IDCLIENTES)
			FETCH CR_INSERT_VENDAS INTO @IDVENDA, @CODVENDA, @DATAVENDA, @VALOR, @QUANTIDADE,@IDVENDEDORES, @IDCLIENTES
		END
	CLOSE CR_INSERT_VENDAS
	DEALLOCATE CR_INSERT_VENDAS
END

SELECT * FROM TB_Vendas
select * from TB_Vendas_AUX
INSERT INTO TB_Vendas (cod_Venda, dataVenda, valor, quantidade,idVendedores,idCliente) VALUES (1234,'20170924',500,5,1,1)
SELECT * FROM TB_Vendedores
SELECT * FROM TB_Cliente
							
								 
EXEC SP_OLTP_TB_VENDAS_AUX '20170924'	 
--------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------
--CARGA DA TB_TIPO_LOCACAO PARA STAGING TB_LOCACAO_AUX
------------------------------------------------------------------

ALTER PROCEDURE SP_OLTP_TB_LOCACAO_AUX (@DATACARGA DATETIME)
AS
BEGIN
 DELETE FROM TB_Locacao_AUX WHERE  DATA_CARGA = @DATACARGA
DECLARE @IDLOCACAO INT, @CODLOCACAO INT, @DATALOCACAO DATETIME, @VALORLOCACAO NUMERIC(10,2), @QUANTIDADE INT, @IDVENDEDORES INT, @IDCLIENTES INT
DECLARE CR_INSERT_LOCACAO CURSOR FOR SELECT TL.idLocacao, TL.cod_Locacao, TL.data_Locacao, TL.valorLocacao, TL.quantidade, TL.idVendedores, TL.idCliente FROM TB_Locacao TL;
	OPEN CR_INSERT_LOCACAO

		FETCH CR_INSERT_LOCACAO INTO @IDLOCACAO, @CODLOCACAO, @DATALOCACAO, @VALORLOCACAO, @QUANTIDADE, @IDVENDEDORES, @IDCLIENTES
		WHILE(@@FETCH_STATUS = 0 )
		BEGIN
			INSERT TB_Locacao_AUX (idLocacao,DATA_CARGA,cod_Locacao,data_Locacao,valorLocacao,QUANTIDADE,idVendedores, idCliente) VALUES (@IDLOCACAO,@DATACARGA ,@CODLOCACAO, @DATALOCACAO, @VALORLOCACAO, @QUANTIDADE,@IDVENDEDORES, @IDCLIENTES)
			FETCH CR_INSERT_LOCACAO INTO @IDLOCACAO, @CODLOCACAO, @DATALOCACAO, @VALORLOCACAO, @QUANTIDADE, @IDVENDEDORES, @IDCLIENTES
		END
	CLOSE CR_INSERT_LOCACAO
	DEALLOCATE CR_INSERT_LOCACAO
END

SELECT * FROM TB_Locacao
select * from TB_Locacao_AUX
INSERT INTO TB_Locacao (cod_Locacao, data_Locacao, valorLocacao, quantidade,idVendedores,idCliente) VALUES (1234,'20170924',500,5,1,1)
SELECT * FROM TB_Vendedores
SELECT * FROM TB_Cliente
							
								 
EXEC SP_OLTP_TB_LOCACAO_AUX '20170924'